PRODUCT_PACKAGES += \
    android.hardware.audio.common-util \
    android.hardware.audio.common@2.0-util \
    android.hardware.audio.common@4.0-util \
    android.hardware.audio.common@5.0-util \
    android.hardware.audio.common@6.0-util \
    android.hardware.audio.effect@2.0-impl \
    android.hardware.audio.effect@4.0-impl \
    android.hardware.audio.effect@5.0-impl \
    android.hardware.audio.effect@6.0-impl \
    android.hardware.audio@2.0-impl \
    android.hardware.audio@4.0-impl \
    android.hardware.audio@5.0-impl \
    android.hardware.audio@6.0-impl \
    android.hardware.automotive.vehicle@2.0-manager-lib \
    android.hardware.biometrics.fingerprint@2.1 \
    android.hardware.biometrics.fingerprint@2.1-service \
    android.hardware.bluetooth.audio@2.0-impl \
    android.hardware.camera.provider@2.4-external \
    android.hardware.camera.provider@2.4-impl \
    android.hardware.camera.provider@2.4-legacy \
    android.hardware.gnss.measurement_corrections@1.0 \
    android.hardware.gnss.measurement_corrections@1.1 \
    android.hardware.gnss.visibility_control@1.0 \
    android.hardware.gnss@1.0 \
    android.hardware.gnss@1.1 \
    android.hardware.gnss@2.0 \
    android.hardware.gnss@2.1 \
    android.hardware.gnss@2.1-service-qti \
    android.hardware.graphics.mapper@3.0-impl-qti-display \
    android.hardware.graphics.mapper@4.0-impl-qti-display \
    android.hardware.lights-service.qti \
    android.hardware.memtrack@1.0-impl \
    android.hardware.renderscript@1.0-impl \
    android.hardware.sensors@2.0 \
    android.hardware.sensors@2.0-ScopedWakelock \
    android.hardware.sensors@2.0-service.multihal \
    android.hardware.soundtrigger@2.1-impl \
    android.hardware.soundtrigger@2.2-impl \
    android.hardware.thermal@2.0-service.qti \
    android.system.suspend@1.0-service \
    audio.bluetooth.default \
    audio.primary.default \
    audio.r_submix.default \
    audio.usb.default \
    camera.device@1.0-impl \
    camera.device@3.2-impl \
    camera.device@3.3-impl \
    camera.device@3.4-external-impl \
    camera.device@3.4-impl \
    camera.device@3.5-external-impl \
    camera.device@3.5-impl \
    camera.device@3.6-external-impl \
    com.dsi.ant@1.0 \
    com.qualcomm.qti.bluetooth_audio@1.0 \
    cplay \
    fingerprint.default \
    gralloc.default \
    init.qti.media.sh \
    ipacm \
    ipacm-diag \
    liba2dpoffload \
    libalsautils \
    libaudiopreprocessing \
    libavservices_minijail \
    libavservices_minijail_vendor \
    libbatterylistener \
    libbluetooth_audio_session \
    libbundlewrapper \
    libc2dcolorconvert \
    libchrome \
    libcirrusspkrprot \
    libcld80211 \
    libclearkeycasplugin \
    libcodec2_hidl@1.0 \
    libcodec2_vndk \
    libcomprcapture \
    libdisplayconfig.qti \
    libdisplaydebug \
    libdownmix \
    libdrm \
    libdrmclearkeyplugin \
    libdrmutils \
    libdynproc \
    libeffectproxy \
    libeffects \
    libeffectsconfig \
    libexthwplugin \
    libfastcvopt \
    libgpu_tonemapper \
    libgralloc.qti \
    libgralloccore \
    libgrallocutils \
    libgui_vendor \
    libhdmiedid \
    libhfp \
    libhidlbase \
    libhidltransport \
    libhistogram \
    libhwbinder \
    libhwminijail \
    libipanat \
    libjson \
    libkeystore-engine-wifi-hidl \
    libkeystore-wifi-hidl \
    libldnhncr \
    liblog \
    libmm-omxcore \
    libnbaio_mono \
    libnetfilter_conntrack \
    libnfnetlink \
    liboffloadhal \
    libopus \
    libplatformconfig \
    libqcompostprocbundle \
    libqcomvisualizer \
    libqcomvoiceprocessing \
    libqdMetaData \
    libqdutils \
    libqservice \
    libqti_vndfwk_detect \
    libqtivibratoreffect \
    libreference-ril \
    libreverbwrapper \
    libril \
    librilutils \
    librmnetctl \
    libsdedrm \
    libsdmcore \
    libsdmutils \
    libsensorndkbridge \
    libsndmonitor \
    libspkrprot \
    libstagefright_amrnb_common \
    libstagefright_bufferpool@2.0.1 \
    libstagefright_enc_common \
    libstagefright_flacdec \
    libstagefright_soft_aacdec \
    libstagefright_soft_aacenc \
    libstagefright_soft_amrdec \
    libstagefright_soft_amrnbenc \
    libstagefright_soft_amrwbenc \
    libstagefright_soft_avcdec \
    libstagefright_soft_avcenc \
    libstagefright_soft_flacdec \
    libstagefright_soft_flacenc \
    libstagefright_soft_g711dec \
    libstagefright_soft_gsmdec \
    libstagefright_soft_hevcdec \
    libstagefright_soft_mp3dec \
    libstagefright_soft_mpeg2dec \
    libstagefright_soft_mpeg4dec \
    libstagefright_soft_mpeg4enc \
    libstagefright_soft_opusdec \
    libstagefright_soft_rawdec \
    libstagefright_soft_vorbisdec \
    libstagefright_soft_vpxdec \
    libstagefright_soft_vpxenc \
    libstagefright_softomx \
    libstagefright_softomx_plugin \
    libstagefrighthw \
    libthermalclient \
    libtinycompress \
    libtinyxml \
    libutils \
    libvisualizer \
    libvndfwk_detect_jni.qti \
    libvolumelistener \
    libvorbisidec \
    libvpx \
    libwebrtc_audio_preprocessing \
    libwfdaac_vendor \
    libwifi-hal \
    local_time.default \
    power.default \
    vendor.display.config@1.0 \
    vendor.display.config@1.1 \
    vendor.display.config@1.10 \
    vendor.display.config@1.11 \
    vendor.display.config@1.2 \
    vendor.display.config@1.3 \
    vendor.display.config@1.4 \
    vendor.display.config@1.5 \
    vendor.display.config@1.6 \
    vendor.display.config@1.7 \
    vendor.display.config@1.8 \
    vendor.display.config@1.9 \
    vendor.display.config@2.0 \
    vendor.nxp.hardware.nfc@1.0 \
    vendor.nxp.hardware.nfc@1.1 \
    vendor.qti.hardware.audiohalext@1.0 \
    vendor.qti.hardware.bluetooth_audio@2.0 \
    vendor.qti.hardware.btconfigstore@1.0 \
    vendor.qti.hardware.camera.device@1.0 \
    vendor.qti.hardware.camera.postproc@1.0 \
    vendor.qti.hardware.capabilityconfigstore@1.0 \
    vendor.qti.hardware.display.allocator \
    vendor.qti.hardware.display.allocator@1.0 \
    vendor.qti.hardware.display.allocator@3.0 \
    vendor.qti.hardware.display.allocator@4.0 \
    vendor.qti.hardware.display.composer-service \
    vendor.qti.hardware.display.composer@1.0 \
    vendor.qti.hardware.display.composer@2.0 \
    vendor.qti.hardware.display.composer@3.0 \
    vendor.qti.hardware.display.mapper@1.0 \
    vendor.qti.hardware.display.mapper@1.1 \
    vendor.qti.hardware.display.mapper@2.0 \
    vendor.qti.hardware.display.mapper@3.0 \
    vendor.qti.hardware.display.mapper@4.0 \
    vendor.qti.hardware.display.mapperextensions@1.0 \
    vendor.qti.hardware.display.mapperextensions@1.1 \
    vendor.qti.hardware.fstman@1.0 \
    vendor.qti.hardware.perf@2.0 \
    android.hardware.power-service-qti \
    vendor.qti.hardware.servicetracker@1.0 \
    vendor.qti.hardware.servicetracker@1.1 \
    vendor.qti.hardware.servicetracker@1.2 \
    vendor.qti.hardware.systemhelper@1.0 \
    vendor.qti.hardware.vibrator.impl \
    vendor.qti.hardware.vibrator.service \
    vibrator.default

